name: my-first-actions
run-name: ${{ github.actor }} is testing out GitHub Actions
on: 
  workflow_dispatch:
    inputs:
      opt:
        description: "opt: need user input a value"
        required: true
        default: "0"
        type: choice
        options:
        - 1
        - 2
      environment:
        description: "environment opt"
        type: environment
        required: false
        
jobs:
  hello-world-1:
    runs-on: ubuntu-latest
    env: 
      name: "jgc"
    steps: 
      - name: Print env
        env:
          age: 24
        run: |
          echo $name
          echo $age
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Print inputs
      	env:
          OPTIONS: ${{inputs.opt}}
          ENVIRONMENT: ${{inputs.environment}}
        run: |
          echo "opt: $OPTIONS"
          echo "environment: $ENVIRONMENT"     
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: npm install
        run: npm install -g
      - name: npm install
        run: npm -v > output.txt
        
  hello-world-2:
    runs-on: windows-latest
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.1
      - name: Compile and run some Code
        shell: cmd
        run: |
          cl.exe HelloWorld.cpp
          HelloWorld.exe
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: "HelloWorld"
          path: "./HelloWorld.exe"

